scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['app:3000']
        labels:
          service: 'app-exporter'
          group: 'testing'
          name: 'app-exporter'