scrape_configs:
  - job_name: 'prometheus_worker'
    scrape_interval: 60s
    metrics_path: /api/metrics
    static_configs:
      - targets: ['service_application:3000']
        labels:
          service: 'prometheus_worker'
          group: 'universe'
          name: 'prometheus_worker'